// <auto-generated />
using System;
using APIChallengeProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIChallengeProject.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220616022957_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APIChallengeProject.Models.Aircraft", b =>
                {
                    b.Property<int>("AircraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AircraftId"), 1L, 1);

                    b.Property<double>("CurrentHours")
                        .HasColumnType("float");

                    b.Property<double>("DailyHours")
                        .HasColumnType("float");

                    b.HasKey("AircraftId");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("APIChallengeProject.Models.AircraftTask", b =>
                {
                    b.Property<int>("ItemNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemNumber"), 1L, 1);

                    b.Property<int?>("AircraftId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IntervalHours")
                        .HasColumnType("int");

                    b.Property<int?>("IntervalMonths")
                        .HasColumnType("int");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LogHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextDue")
                        .HasColumnType("datetime2");

                    b.HasKey("ItemNumber");

                    b.HasIndex("AircraftId");

                    b.ToTable("AircraftTasks");
                });

            modelBuilder.Entity("APIChallengeProject.Models.AircraftTask", b =>
                {
                    b.HasOne("APIChallengeProject.Models.Aircraft", null)
                        .WithMany("AircraftTasks")
                        .HasForeignKey("AircraftId");
                });

            modelBuilder.Entity("APIChallengeProject.Models.Aircraft", b =>
                {
                    b.Navigation("AircraftTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
